# - Run the transform
# - Produce RDF? (use kgx)
# - [Not Yet] QC/Validation (ex. 0 rows)
# - Create release, upload output files as release artifacts

name: Create Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: poetry install --no-interaction

      - name: Run Transform
        run: |
          make run
          poetry run python scripts/generate-rdf.py

      - name: Dynamically set MY_DATE environment variable
        run: echo "DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.DATE }}
          files: |
            output/*
